#!/bin/bash

fname="main"
compiler_bin=/bin/g++
file_extension=""
run_executable=true

winopts(){
    compiler_bin=/bin/x86_64-w64-mingw32-g++
    file_extension=".exe"
    run_executable=false
}

while [ $# -gt 0 ]; do
    case $1 in
        -w | --windows) winopts ;;
        -n | --name) fname=$2 ;;
        -N | --no-run) run_executable=false ;;
    esac
    shift
done


$compiler_bin $fname.cpp -o $fname$file_extension 
if [ $run_executable == true ]
then
    chmod +x $fname && ./$fname
fi

exit
